[2022-05-26 09:45:42,601] {scheduler_job.py:181} INFO - Started process (PID=138) to work on /opt/airflow/dags/init.py
[2022-05-26 09:45:42,632] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:45:42,683] {logging_mixin.py:104} INFO - [2022-05-26 09:45:42,656] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:45:43,005] {logging_mixin.py:104} INFO - [2022-05-26 09:45:42,968] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:45:43,020] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:45:43,629] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 1.150 seconds
[2022-05-26 09:46:39,242] {scheduler_job.py:181} INFO - Started process (PID=179) to work on /opt/airflow/dags/init.py
[2022-05-26 09:46:39,307] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:46:39,321] {logging_mixin.py:104} INFO - [2022-05-26 09:46:39,321] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:46:39,673] {logging_mixin.py:104} INFO - [2022-05-26 09:46:39,603] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:46:39,712] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:46:40,216] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 1.065 seconds
[2022-05-26 09:47:33,928] {scheduler_job.py:181} INFO - Started process (PID=219) to work on /opt/airflow/dags/init.py
[2022-05-26 09:47:33,969] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:47:33,999] {logging_mixin.py:104} INFO - [2022-05-26 09:47:33,999] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:47:34,198] {logging_mixin.py:104} INFO - [2022-05-26 09:47:34,174] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:47:34,229] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:47:34,426] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.563 seconds
[2022-05-26 09:48:29,608] {scheduler_job.py:181} INFO - Started process (PID=253) to work on /opt/airflow/dags/init.py
[2022-05-26 09:48:29,688] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:48:29,704] {logging_mixin.py:104} INFO - [2022-05-26 09:48:29,697] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:48:29,941] {logging_mixin.py:104} INFO - [2022-05-26 09:48:29,911] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:48:29,972] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:48:30,187] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.660 seconds
[2022-05-26 09:51:33,025] {scheduler_job.py:181} INFO - Started process (PID=442) to work on /opt/airflow/dags/init.py
[2022-05-26 09:51:33,037] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:51:33,046] {logging_mixin.py:104} INFO - [2022-05-26 09:51:33,046] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:51:33,320] {logging_mixin.py:104} INFO - [2022-05-26 09:51:33,246] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:51:33,358] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:51:33,680] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.680 seconds
[2022-05-26 09:52:04,313] {scheduler_job.py:181} INFO - Started process (PID=498) to work on /opt/airflow/dags/init.py
[2022-05-26 09:52:04,328] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:52:04,332] {logging_mixin.py:104} INFO - [2022-05-26 09:52:04,332] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:52:04,388] {logging_mixin.py:104} INFO - [2022-05-26 09:52:04,380] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:52:04,398] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:52:04,453] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.152 seconds
[2022-05-26 09:52:35,056] {scheduler_job.py:181} INFO - Started process (PID=551) to work on /opt/airflow/dags/init.py
[2022-05-26 09:52:35,061] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:52:35,067] {logging_mixin.py:104} INFO - [2022-05-26 09:52:35,064] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:52:35,254] {logging_mixin.py:104} INFO - [2022-05-26 09:52:35,236] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:52:35,270] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:52:35,324] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.283 seconds
[2022-05-26 09:53:05,632] {scheduler_job.py:181} INFO - Started process (PID=603) to work on /opt/airflow/dags/init.py
[2022-05-26 09:53:05,637] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:53:05,641] {logging_mixin.py:104} INFO - [2022-05-26 09:53:05,640] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:53:05,678] {logging_mixin.py:104} INFO - [2022-05-26 09:53:05,673] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:53:05,684] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:53:05,733] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.109 seconds
[2022-05-26 09:53:35,891] {scheduler_job.py:181} INFO - Started process (PID=651) to work on /opt/airflow/dags/init.py
[2022-05-26 09:53:35,896] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:53:35,899] {logging_mixin.py:104} INFO - [2022-05-26 09:53:35,898] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:53:35,931] {logging_mixin.py:104} INFO - [2022-05-26 09:53:35,927] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:53:35,937] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:53:35,973] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.089 seconds
[2022-05-26 09:54:06,069] {scheduler_job.py:181} INFO - Started process (PID=707) to work on /opt/airflow/dags/init.py
[2022-05-26 09:54:06,081] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:54:06,089] {logging_mixin.py:104} INFO - [2022-05-26 09:54:06,088] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:54:06,152] {logging_mixin.py:104} INFO - [2022-05-26 09:54:06,146] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:54:06,162] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:54:06,265] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.209 seconds
[2022-05-26 09:54:43,772] {scheduler_job.py:181} INFO - Started process (PID=744) to work on /opt/airflow/dags/init.py
[2022-05-26 09:54:43,801] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:54:43,806] {logging_mixin.py:104} INFO - [2022-05-26 09:54:43,806] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:54:43,998] {logging_mixin.py:104} INFO - [2022-05-26 09:54:43,974] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:54:44,013] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:54:44,121] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.398 seconds
[2022-05-26 09:55:14,786] {scheduler_job.py:181} INFO - Started process (PID=799) to work on /opt/airflow/dags/init.py
[2022-05-26 09:55:14,803] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:55:14,808] {logging_mixin.py:104} INFO - [2022-05-26 09:55:14,808] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:55:14,930] {logging_mixin.py:104} INFO - [2022-05-26 09:55:14,918] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:55:14,943] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:55:15,013] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.246 seconds
[2022-05-26 09:55:49,014] {scheduler_job.py:181} INFO - Started process (PID=854) to work on /opt/airflow/dags/init.py
[2022-05-26 09:55:49,031] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:55:49,041] {logging_mixin.py:104} INFO - [2022-05-26 09:55:49,041] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:55:49,132] {logging_mixin.py:104} INFO - [2022-05-26 09:55:49,121] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:55:49,143] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:55:49,267] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.260 seconds
[2022-05-26 09:56:37,015] {scheduler_job.py:181} INFO - Started process (PID=895) to work on /opt/airflow/dags/init.py
[2022-05-26 09:56:37,042] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:56:37,058] {logging_mixin.py:104} INFO - [2022-05-26 09:56:37,057] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:56:37,402] {logging_mixin.py:104} INFO - [2022-05-26 09:56:37,377] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:56:37,477] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:56:37,749] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.810 seconds
[2022-05-26 09:57:39,556] {scheduler_job.py:181} INFO - Started process (PID=958) to work on /opt/airflow/dags/init.py
[2022-05-26 09:57:39,576] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:57:39,596] {logging_mixin.py:104} INFO - [2022-05-26 09:57:39,596] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:57:39,863] {logging_mixin.py:104} INFO - [2022-05-26 09:57:39,848] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:57:39,893] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:57:42,650] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 3.175 seconds
[2022-05-26 09:58:21,635] {scheduler_job.py:181} INFO - Started process (PID=998) to work on /opt/airflow/dags/init.py
[2022-05-26 09:58:21,640] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:58:21,679] {logging_mixin.py:104} INFO - [2022-05-26 09:58:21,661] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:58:22,070] {logging_mixin.py:104} INFO - [2022-05-26 09:58:22,046] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:58:22,099] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:58:22,442] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.872 seconds
[2022-05-26 09:58:55,414] {scheduler_job.py:181} INFO - Started process (PID=1037) to work on /opt/airflow/dags/init.py
[2022-05-26 09:58:55,457] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 09:58:55,475] {logging_mixin.py:104} INFO - [2022-05-26 09:58:55,475] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 09:58:57,253] {logging_mixin.py:104} INFO - [2022-05-26 09:58:57,108] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 09:58:57,296] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 09:59:04,305] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 8.972 seconds
[2022-05-26 10:00:10,118] {scheduler_job.py:181} INFO - Started process (PID=1099) to work on /opt/airflow/dags/init.py
[2022-05-26 10:00:10,150] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:00:10,170] {logging_mixin.py:104} INFO - [2022-05-26 10:00:10,169] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:00:10,409] {logging_mixin.py:104} INFO - [2022-05-26 10:00:10,397] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 10:00:10,473] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:00:10,760] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.778 seconds
[2022-05-26 10:01:38,331] {scheduler_job.py:181} INFO - Started process (PID=1160) to work on /opt/airflow/dags/init.py
[2022-05-26 10:01:38,359] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:01:38,385] {logging_mixin.py:104} INFO - [2022-05-26 10:01:38,385] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:01:38,645] {logging_mixin.py:104} INFO - [2022-05-26 10:01:38,622] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 10:01:38,688] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:01:39,028] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 0.755 seconds
[2022-05-26 10:03:13,100] {scheduler_job.py:181} INFO - Started process (PID=1214) to work on /opt/airflow/dags/init.py
[2022-05-26 10:03:13,132] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:03:13,147] {logging_mixin.py:104} INFO - [2022-05-26 10:03:13,147] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:03:13,692] {logging_mixin.py:104} INFO - [2022-05-26 10:03:13,663] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 10:03:13,723] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:03:14,339] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 1.403 seconds
[2022-05-26 10:04:46,092] {scheduler_job.py:181} INFO - Started process (PID=1301) to work on /opt/airflow/dags/init.py
[2022-05-26 10:04:46,743] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:04:47,272] {logging_mixin.py:104} INFO - [2022-05-26 10:04:47,263] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:04:48,110] {logging_mixin.py:104} INFO - [2022-05-26 10:04:48,058] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 23, in <module>
    **os.environ
NameError: name 'os' is not defined
[2022-05-26 10:04:48,152] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:04:51,424] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 4.571 seconds
[2022-05-26 10:05:33,135] {scheduler_job.py:181} INFO - Started process (PID=1341) to work on /opt/airflow/dags/init.py
[2022-05-26 10:05:33,197] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:05:33,237] {logging_mixin.py:104} INFO - [2022-05-26 10:05:33,236] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:05:34,671] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:06:37,024] {scheduler_job.py:181} INFO - Started process (PID=1383) to work on /opt/airflow/dags/init.py
[2022-05-26 10:06:37,059] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:06:37,087] {logging_mixin.py:104} INFO - [2022-05-26 10:06:37,086] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:06:37,605] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:07:18,547] {logging_mixin.py:104} INFO - [2022-05-26 10:07:18,547] {opentelemetry_tracing.py:29} INFO - This service is instrumented using OpenTelemetry. OpenTelemetry could not be imported; please add opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
[2022-05-26 10:13:09,290] {scheduler_job.py:181} INFO - Started process (PID=131) to work on /opt/airflow/dags/init.py
[2022-05-26 10:13:09,338] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:13:09,373] {logging_mixin.py:104} INFO - [2022-05-26 10:13:09,372] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:13:09,701] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:13:13,548] {logging_mixin.py:104} INFO - [2022-05-26 10:13:13,547] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:13:13,942] {logging_mixin.py:104} INFO - [2022-05-26 10:13:13,929] {dag.py:1852} INFO - Creating ORM DAG for 1_init_once_seed_data
[2022-05-26 10:13:14,038] {logging_mixin.py:104} INFO - [2022-05-26 10:13:14,038] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:13:14,344] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 5.136 seconds
[2022-05-26 10:14:04,549] {scheduler_job.py:181} INFO - Started process (PID=178) to work on /opt/airflow/dags/init.py
[2022-05-26 10:14:04,569] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:14:04,588] {logging_mixin.py:104} INFO - [2022-05-26 10:14:04,588] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:14:04,938] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:14:05,243] {logging_mixin.py:104} INFO - [2022-05-26 10:14:05,243] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:14:05,407] {logging_mixin.py:104} INFO - [2022-05-26 10:14:05,406] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:14:05,515] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 1.078 seconds
[2022-05-26 10:15:03,262] {scheduler_job.py:181} INFO - Started process (PID=231) to work on /opt/airflow/dags/init.py
[2022-05-26 10:15:03,324] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:15:03,346] {logging_mixin.py:104} INFO - [2022-05-26 10:15:03,346] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:15:04,056] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:15:04,749] {logging_mixin.py:104} INFO - [2022-05-26 10:15:04,749] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:15:05,156] {logging_mixin.py:104} INFO - [2022-05-26 10:15:05,156] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:15:05,323] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 2.219 seconds
[2022-05-26 10:16:03,350] {scheduler_job.py:181} INFO - Started process (PID=268) to work on /opt/airflow/dags/init.py
[2022-05-26 10:16:03,369] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:16:03,420] {logging_mixin.py:104} INFO - [2022-05-26 10:16:03,420] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:16:04,333] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:16:04,960] {logging_mixin.py:104} INFO - [2022-05-26 10:16:04,959] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:16:05,191] {logging_mixin.py:104} INFO - [2022-05-26 10:16:05,191] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:16:05,374] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 2.315 seconds
[2022-05-26 10:17:03,643] {scheduler_job.py:181} INFO - Started process (PID=312) to work on /opt/airflow/dags/init.py
[2022-05-26 10:17:03,707] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:17:03,782] {logging_mixin.py:104} INFO - [2022-05-26 10:17:03,719] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:17:04,534] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:17:05,094] {logging_mixin.py:104} INFO - [2022-05-26 10:17:05,093] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:17:05,501] {logging_mixin.py:104} INFO - [2022-05-26 10:17:05,500] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:17:05,698] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 2.227 seconds
[2022-05-26 10:18:15,735] {scheduler_job.py:181} INFO - Started process (PID=353) to work on /opt/airflow/dags/init.py
[2022-05-26 10:18:15,765] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:18:15,905] {logging_mixin.py:104} INFO - [2022-05-26 10:18:15,905] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:18:18,298] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:18:21,712] {logging_mixin.py:104} INFO - [2022-05-26 10:18:21,712] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:18:22,531] {logging_mixin.py:104} INFO - [2022-05-26 10:18:22,530] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:18:22,797] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 7.283 seconds
[2022-05-26 10:19:14,083] {scheduler_job.py:181} INFO - Started process (PID=397) to work on /opt/airflow/dags/init.py
[2022-05-26 10:19:14,157] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:19:14,233] {logging_mixin.py:104} INFO - [2022-05-26 10:19:14,233] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:19:15,521] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:19:16,219] {logging_mixin.py:104} INFO - [2022-05-26 10:19:16,219] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:19:16,581] {logging_mixin.py:104} INFO - [2022-05-26 10:19:16,581] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:19:16,796] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 2.902 seconds
[2022-05-26 10:20:29,599] {scheduler_job.py:181} INFO - Started process (PID=432) to work on /opt/airflow/dags/init.py
[2022-05-26 10:20:29,668] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:20:29,676] {logging_mixin.py:104} INFO - [2022-05-26 10:20:29,675] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:20:32,114] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:20:33,593] {logging_mixin.py:104} INFO - [2022-05-26 10:20:33,593] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:20:34,093] {logging_mixin.py:104} INFO - [2022-05-26 10:20:34,093] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:20:34,742] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 10.254 seconds
[2022-05-26 10:22:09,499] {scheduler_job.py:181} INFO - Started process (PID=481) to work on /opt/airflow/dags/init.py
[2022-05-26 10:22:09,697] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-05-26 10:22:09,753] {logging_mixin.py:104} INFO - [2022-05-26 10:22:09,752] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-05-26 10:22:18,053] {scheduler_job.py:642} INFO - DAG(s) dict_keys(['1_init_once_seed_data']) retrieved from /opt/airflow/dags/init.py
[2022-05-26 10:22:19,707] {logging_mixin.py:104} INFO - [2022-05-26 10:22:19,706] {dag.py:1833} INFO - Sync 1 DAGs
[2022-05-26 10:22:20,998] {logging_mixin.py:104} INFO - [2022-05-26 10:22:20,998] {dag.py:2306} INFO - Setting next_dagrun for 1_init_once_seed_data to 2020-08-01T00:00:00+00:00
[2022-05-26 10:22:21,535] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/init.py took 12.389 seconds
